In [4]:
import pandas as pd

In [11]:
df = pd.read_csv('tamheer_2022.csv')

In [31]:
df.shape

(112615, 20)

In [22]:
df.head()

,ID,جنس المتدرب,مدينة المتدرب,منطقة المتدرب,تخصص المتدرب,مؤهل المتدرب,معدل المتدرب,المعدل من,عمر المتدرب,تاريخ بداية التدريب,تاريخ نهاية التدريب,حالة المتدرب,اسم الفرصه التدريبية,النشاط الاقتصادي للفرصة التدريبية,مؤهل التدريب,تاريخ الانتهاء,تاريخ الانسحاب,حجم مؤسسة التدريب,النشاط الاقتصادي لمؤسسة التدريب,المؤسسة التعليمية للمتدرب
0,1,ذكر,تيماء,تبوك,NaN,البكالوريوس أو ما يعادلها,2.57,0.0,40,NaN,NaN,مسجل,أخصائي تطوير إداري - منطقة تبوك,أخصائي تطوير إداري,بكالوريوس أو أعلى,1900-01-01 00:00:00,NaN,كبيرة,NaN,Study Group (Embassy CES) - Sydney
1,2,انثى,ام نخيلة,الجوف,علوم الحاسب الآلي والمعلوماتية,دكتوراه,88.93,0.0,51,NaN,NaN,مسجل,مبرمج,محلل مبرمج,بكالوريوس أو أعلى,1900-01-01 00:00:00,NaN,كبيرة,NaN,OAKLAND UNIVERSITY
2,3,ذكر,الخرخير,نجران,الهندسة المدنية,بكالوريوس,2.05,0.0,37,NaN,NaN,مسجل,هندسة مدنية,مهندس مدني,بكالوريوس أو أعلى,1900-01-01 00:00:00,NaN,عملاقة,نقل المياة عبر خطوط الانابيب,جامعة أم القرى
3,4,ذكر,الخرخير,نجران,الهندسة المدنية,بكالوريوس,2.05,0.0,37,NaN,NaN,مسجل,مهندس مدني مؤسسه مقاولات,مهندس مدني,بكالوريوس أو أعلى,1900-01-01 00:00:00,NaN,صغيرة فئة ب,الإنشاءات العامة للمباني السكنية,جامعة أم القرى
4,5,ذكر,الخرخير,نجران,الهندسة المدنية,بكالوريوس,2.05,0.0,37,NaN,NaN,مسجل,مهندس مدني - الخدمات العامة,مهندس مدني,بكالوريوس أو أعلى,1900-01-01 00:00:00,NaN,كبيرة,NaN,جامعة أم القرى

In [23]:
df.tail()

,ID,جنس المتدرب,مدينة المتدرب,منطقة المتدرب,تخصص المتدرب,مؤهل المتدرب,معدل المتدرب,المعدل من,عمر المتدرب,تاريخ بداية التدريب,تاريخ نهاية التدريب,حالة المتدرب,اسم الفرصه التدريبية,النشاط الاقتصادي للفرصة التدريبية,مؤهل التدريب,تاريخ الانتهاء,تاريخ الانسحاب,حجم مؤسسة التدريب,النشاط الاقتصادي لمؤسسة التدريب,المؤسسة التعليمية للمتدرب
112610,112611,انثى,ابها,عسير,نظم المعلومات,بكالوريوس,4.13,0.0,24,NaN,NaN,متدرب نشط,تعلن هيئة الهلال الأحمر السعودي فرع منطقة عسير...,أخصائي إدارة مشاريع,بكالوريوس أو أعلى,1900-01-01 00:00:00,NaN,كبيرة,NaN,جامعة الملك خالد
112611,112612,انثى,ابها,عسير,نظم المعلومات,بكالوريوس,4.13,0.0,24,NaN,NaN,متدرب نشط,أخصائي إستمرارية الأعمال,أخصائي استمرارية الأعمال,بكالوريوس أو أعلى,1900-01-01 00:00:00,NaN,عملاقة,الخدمات الطبية بالمصحات المتخصصة ومراكز إعادة ...,جامعة الملك خالد
112612,112613,انثى,ابها,عسير,نظم المعلومات,بكالوريوس,4.13,0.0,24,NaN,NaN,متدرب نشط,اخصائي موارد بشرية,أخصائي عمليات موارد بشرية,بكالوريوس أو أعلى,1900-01-01 00:00:00,NaN,متوسطة فئة أ,أنشطة خدمات صيانة المباني,جامعة الملك خالد
112613,112614,انثى,ابها,عسير,نظم المعلومات,بكالوريوس,4.13,0.0,24,NaN,NaN,متدرب نشط,اخصائي خدمة العملاء,أخصائي خدمة عملاء,بكالوريوس أو أعلى,1900-01-01 00:00:00,NaN,كبيرة,خدمات الاختبارات والتقييم,جامعة الملك خالد
112614,112615,انثى,ابها,عسير,نظم المعلومات,بكالوريوس,4.13,0.0,24,NaN,NaN,متدرب نشط,خدمة عملاء,أخصائي خدمة عملاء,بكالوريوس أو أعلى,1900-01-01 00:00:00,NaN,صغيرة فئة ب,الخدمات الطبية بالمصحات المتخصصة ومراكز إعادة ...,جامعة الملك خالد

In [24]:
df.dtypes

ID                                     int64
جنس المتدرب                           object
مدينة المتدرب                         object
منطقة المتدرب                         object
تخصص المتدرب                          object
مؤهل المتدرب                          object
معدل المتدرب                         float64
المعدل من                            float64
عمر المتدرب                            int64
تاريخ بداية التدريب                   object
تاريخ نهاية التدريب                   object
حالة المتدرب                          object
اسم الفرصه التدريبية                  object
النشاط الاقتصادي للفرصة التدريبية     object
مؤهل التدريب                          object
تاريخ الانتهاء                        object
تاريخ الانسحاب                        object
حجم مؤسسة التدريب                     object
النشاط الاقتصادي لمؤسسة التدريب       object
المؤسسة التعليمية للمتدرب             object
dtype: object

In [25]:
df.describe()

                 ID  معدل المتدرب     المعدل من    عمر المتدرب
count  112615.00000  97855.000000  97855.000000  112615.000000
mean    56308.00000      5.762873      1.685933      25.604156
std     32509.29462     13.806602      2.280288       2.155375
min         1.00000      0.000000      0.000000      24.000000
25%     28154.50000      2.810000      0.000000      24.000000
50%     56308.00000      3.330000      0.000000      25.000000
75%     84461.50000      4.000000      5.000000      26.000000
max    112615.00000    100.000000      5.000000      55.000000

In [26]:
df.isna().sum()

ID                                        0
جنس المتدرب                             243
مدينة المتدرب                          1229
منطقة المتدرب                          1229
تخصص المتدرب                           6484
مؤهل المتدرب                            199
معدل المتدرب                          14760
المعدل من                             14760
عمر المتدرب                               0
تاريخ بداية التدريب                  111014
تاريخ نهاية التدريب                  111014
حالة المتدرب                              0
اسم الفرصه التدريبية                      2
النشاط الاقتصادي للفرصة التدريبية         0
مؤهل التدريب                              0
تاريخ الانتهاء                            0
تاريخ الانسحاب                       112437
حجم مؤسسة التدريب                         0
النشاط الاقتصادي لمؤسسة التدريب       39207
المؤسسة التعليمية للمتدرب              6462
dtype: int64

In [27]:
df.info

<bound method DataFrame.info of             ID جنس المتدرب مدينة المتدرب منطقة المتدرب  \
0            1         ذكر         تيماء          تبوك
1            2        انثى      ام نخيلة         الجوف
2            3         ذكر       الخرخير         نجران
3            4         ذكر       الخرخير         نجران
4            5         ذكر       الخرخير         نجران
...        ...         ...           ...           ...
112610  112611        انثى          ابها          عسير
112611  112612        انثى          ابها          عسير
112612  112613        انثى          ابها          عسير
112613  112614        انثى          ابها          عسير
112614  112615        انثى          ابها          عسير

                          تخصص المتدرب               مؤهل المتدرب  \
0                                  NaN  البكالوريوس أو ما يعادلها
1       علوم الحاسب الآلي والمعلوماتية                    دكتوراه
2                      الهندسة المدنية                  بكالوريوس
3                      الهندسة المدنية                  بكالوريوس
4                      الهندسة المدنية                  بكالوريوس
...                                ...                        ...
112610                   نظم المعلومات                  بكالوريوس
112611                   نظم المعلومات                  بكالوريوس
112612                   نظم المعلومات                  بكالوريوس
112613                   نظم المعلومات                  بكالوريوس
112614                   نظم المعلومات                  بكالوريوس

        معدل المتدرب  المعدل من  عمر المتدرب تاريخ بداية التدريب  \
0               2.57        0.0           40                 NaN
1              88.93        0.0           51                 NaN
2               2.05        0.0           37                 NaN
3               2.05        0.0           37                 NaN
4               2.05        0.0           37                 NaN
...              ...        ...          ...                 ...
112610          4.13        0.0           24                 NaN
112611          4.13        0.0           24                 NaN
112612          4.13        0.0           24                 NaN
112613          4.13        0.0           24                 NaN
112614          4.13        0.0           24                 NaN

       تاريخ نهاية التدريب حالة المتدرب  \
0                      NaN         مسجل
1                      NaN         مسجل
2                      NaN         مسجل
3                      NaN         مسجل
4                      NaN         مسجل
...                    ...          ...
112610                 NaN    متدرب نشط
112611                 NaN    متدرب نشط
112612                 NaN    متدرب نشط
112613                 NaN    متدرب نشط
112614                 NaN    متدرب نشط

                                     اسم الفرصه التدريبية  \
0                         أخصائي تطوير إداري - منطقة تبوك
1                                                   مبرمج
2                                             هندسة مدنية
3                                مهندس مدني مؤسسه مقاولات
4                            مهندس مدني - الخدمات العامة
...                                                   ...
112610  تعلن هيئة الهلال الأحمر السعودي فرع منطقة عسير...
112611                           أخصائي إستمرارية الأعمال
112612                                اخصائي موارد بشرية
112613                                اخصائي خدمة العملاء
112614                                         خدمة عملاء

       النشاط الاقتصادي للفرصة التدريبية       مؤهل التدريب  \
0                     أخصائي تطوير إداري  بكالوريوس أو أعلى
1                             محلل مبرمج  بكالوريوس أو أعلى
2                             مهندس مدني  بكالوريوس أو أعلى
3                             مهندس مدني  بكالوريوس أو أعلى
4                             مهندس مدني  بكالوريوس أو أعلى
...                                  ...                ...
112610               أخصائي إدارة مشاريع  بكالوريوس أو أعلى
112611          أخصائي استمرارية الأعمال  بكالوريوس أو أعلى
112612         أخصائي عمليات موارد بشرية  بكالوريوس أو أعلى
112613                 أخصائي خدمة عملاء  بكالوريوس أو أعلى
112614                 أخصائي خدمة عملاء  بكالوريوس أو أعلى

             تاريخ الانتهاء تاريخ الانسحاب حجم مؤسسة التدريب  \
0       1900-01-01 00:00:00            NaN             كبيرة
1       1900-01-01 00:00:00            NaN             كبيرة
2       1900-01-01 00:00:00            NaN            عملاقة
3       1900-01-01 00:00:00            NaN       صغيرة فئة ب
4       1900-01-01 00:00:00            NaN             كبيرة
...                     ...            ...               ...
112610  1900-01-01 00:00:00            NaN             كبيرة
112611  1900-01-01 00:00:00            NaN            عملاقة
112612  1900-01-01 00:00:00            NaN      متوسطة فئة أ
112613  1900-01-01 00:00:00            NaN             كبيرة
112614  1900-01-01 00:00:00            NaN       صغيرة فئة ب

                          النشاط الاقتصادي لمؤسسة التدريب  \
0                                                     NaN
1                                                     NaN
2                           نقل المياة عبر خطوط الانابيب
3                        الإنشاءات العامة للمباني السكنية
4                                                     NaN
...                                                   ...
112610                                                NaN
112611  الخدمات الطبية بالمصحات المتخصصة ومراكز إعادة ...
112612                          أنشطة خدمات صيانة المباني
112613                          خدمات الاختبارات والتقييم
112614  الخدمات الطبية بالمصحات المتخصصة ومراكز إعادة ...

                 المؤسسة التعليمية للمتدرب
0       Study Group (Embassy CES) - Sydney
1                       OAKLAND UNIVERSITY
2                           جامعة أم القرى
3                           جامعة أم القرى
4                           جامعة أم القرى
...                                    ...
112610                    جامعة الملك خالد
112611                    جامعة الملك خالد
112612                    جامعة الملك خالد
112613                    جامعة الملك خالد
112614                    جامعة الملك خالد

[112615 rows x 20 columns]>

In [28]:
df.isnull().mean() * 100

ID                                    0.000000
جنس المتدرب                           0.215779
مدينة المتدرب                         1.091329
منطقة المتدرب                         1.091329
تخصص المتدرب                          5.757670
مؤهل المتدرب                          0.176708
معدل المتدرب                         13.106602
المعدل من                            13.106602
عمر المتدرب                           0.000000
تاريخ بداية التدريب                  98.578342
تاريخ نهاية التدريب                  98.578342
حالة المتدرب                          0.000000
اسم الفرصه التدريبية                  0.001776
النشاط الاقتصادي للفرصة التدريبية     0.000000
مؤهل التدريب                          0.000000
تاريخ الانتهاء                        0.000000
تاريخ الانسحاب                       99.841939
حجم مؤسسة التدريب                     0.000000
النشاط الاقتصادي لمؤسسة التدريب      34.815078
المؤسسة التعليمية للمتدرب             5.738134
dtype: float64